In [1]:
# Author: Romain Tavenard
# License: BSD 3 clause

import numpy
import matplotlib.pyplot as plt

from tslearn.clustering import TimeSeriesKMeans
from tslearn.datasets import CachedDatasets
from tslearn.preprocessing import TimeSeriesScalerMeanVariance, \
    TimeSeriesResampler

seed = 0
numpy.random.seed(seed)
X_train, y_train, X_test, y_test = CachedDatasets().load_dataset("Trace")
X_train = X_train[y_train < 4]  # Keep first 3 classes
numpy.random.shuffle(X_train)
# Keep only 50 time series
X_train = TimeSeriesScalerMeanVariance().fit_transform(X_train[:50])
# Make time series shorter
X_train = TimeSeriesResampler(sz=40).fit_transform(X_train)
print('next x train', X_train.shape)
sz = X_train.shape[1]

print(X_train)
# Euclidean k-means
print("Euclidean k-means")
# km = TimeSeriesKMeans(n_clusters=3, verbose=True, random_state=seed)
# y_pred = km.fit_predict(X_train)

# for i in X_train:
#     plt.plot(i)

# plt.figure()
# for yi in range(3):
#     plt.subplot(3, 3, yi + 1)
#     for xx in X_train[y_pred == yi]:
#         plt.plot(xx.ravel(), "k-", alpha=.2)
#     plt.plot(km.cluster_centers_[yi].ravel(), "r-")
#     plt.xlim(0, sz)
#     plt.ylim(-4, 4)
#     if yi == 1:
#         plt.title("Euclidean $k$-means")

# plt.tight_layout()
# plt.show()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.
  warnings.warn(message, FutureWarning)


next x train (50, 40, 1)
[[[ 0.70284807]
  [ 0.67041062]
  [ 0.66094803]
  ...
  [ 0.58290225]
  [ 0.5847045 ]
  [ 0.59973054]]

 [[ 0.78424784]
  [ 0.76968207]
  [ 0.73637576]
  ...
  [ 0.79215738]
  [ 0.77039311]
  [ 0.78639174]]

 [[-1.45424119]
  [-1.47859826]
  [-1.50492559]
  ...
  [ 0.72844694]
  [ 0.72533128]
  [ 0.7094401 ]]

 ...

 [[ 0.75458352]
  [ 0.78165687]
  [ 0.80198359]
  ...
  [ 0.74927489]
  [ 0.7479381 ]
  [ 0.74485583]]

 [[-1.38201243]
  [-1.35633753]
  [-1.37303456]
  ...
  [ 0.76888577]
  [ 0.81197286]
  [ 0.83448894]]

 [[ 0.66455793]
  [ 0.56782604]
  [ 0.65111839]
  ...
  [ 0.55524164]
  [ 0.55725016]
  [ 0.56296336]]]
Euclidean k-means
